export const User = require("./images/github.svg");

const info = [
    {   
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    },
    {
        name:"Member", 
        img:User, 
        tagline:"Tagline", 
        linkedinURL:"", 
        twitterURL:"", 
        githubURL:"", 
        portfolioURL:""
    }
];

export default info;
